# Generated by Django 3.2.4 on 2021-07-09 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_alter_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user',
            new_name='owner',
        ),
    ]
